// ------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated from a template.
// 
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Generated on 2018-02-16T11:10:24, by ESR Version 1.71.0.0 using ESR Database 
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;
using System.Xml;
using System.Collections.Generic;

namespace Ato.EN.IntegrationServices.CodeGenerationPAYEVNT
{
    /// <summary>
    /// PAYEVNT
    /// </summary>
    [DataContract(Name = "PAYEVNT", Namespace = "http://www.sbr.gov.au/ato/payevnt")]
    public class PAYEVNT
    {

        [DataMember(EmitDefaultValue = false, Order = 1)]
        public Rp Rp { get; set; }

        [DataMember(EmitDefaultValue = false, Order = 2)]
        public Int Int { get; set; }
    }

    /// <summary>
    /// Payer Name
    /// </summary>
    [DataContract(Name = "OrganisationName", Namespace = "http://www.sbr.gov.au/ato/payevnt")]
    public class OrganisationName
    {

        /// <summary>
        /// Payer Organisation Name
        /// </summary>
        [DataMember(EmitDefaultValue = false, Order = 1)]
        public string DetailsOrganisationalNameT { get; set; }

        /// <summary>
        /// Payer Contact Name
        /// </summary>
        [DataMember(EmitDefaultValue = false, Order = 2)]
        public string PersonUnstructuredNameFullNameT { get; set; }
    }

    /// <summary>
    /// Payer Electronic Contact
    /// </summary>
    [DataContract(Name = "ElectronicContact", Namespace = "http://www.sbr.gov.au/ato/payevnt")]
    public class ElectronicContact
    {

        /// <summary>
        /// Payer E-mail Address
        /// </summary>
        [DataMember(EmitDefaultValue = false, Order = 1)]
        public string ElectronicMailAddressT { get; set; }

        /// <summary>
        /// Payer Business Hours Phone Number
        /// </summary>
        [DataMember(EmitDefaultValue = false, Order = 2)]
        public string TelephoneMinimalN { get; set; }
    }

    /// <summary>
    /// Payer Postal Address
    /// </summary>
    [DataContract(Name = "AddressDetailsPostal", Namespace = "http://www.sbr.gov.au/ato/payevnt")]
    public class AddressDetailsPostal
    {

        /// <summary>
        /// Payer Address Line 1
        /// </summary>
        [DataMember(EmitDefaultValue = false, Order = 1)]
        public string Line1T { get; set; }

        /// <summary>
        /// Payer Address Line 2
        /// </summary>
        [DataMember(EmitDefaultValue = false, Order = 2)]
        public string Line2T { get; set; }

        /// <summary>
        /// Payer Suburb/Town
        /// </summary>
        [DataMember(EmitDefaultValue = false, Order = 3)]
        public string LocalityNameT { get; set; }

        /// <summary>
        /// Payer State/Territory
        /// </summary>
        [DataMember(EmitDefaultValue = false, Order = 4)]
        public string StateOrTerritoryC { get; set; }

        /// <summary>
        /// Payer Postcode
        /// </summary>
        [DataMember(EmitDefaultValue = false, Order = 5)]
        public string PostcodeT { get; set; }

        /// <summary>
        /// Payer Country Code
        /// </summary>
        [DataMember(EmitDefaultValue = false, Order = 6)]
        public string CountryC { get; set; }
    }

    /// <summary>
    /// Payer Period Totals
    /// </summary>
    [DataContract(Name = "IncomeTaxAndRemuneration", Namespace = "http://www.sbr.gov.au/ato/payevnt")]
    public class IncomeTaxAndRemuneration
    {

        /// <summary>
        /// Payer Total PAYGW Amount
        /// </summary>
        [DataMember(EmitDefaultValue = false, Order = 1)]
        public decimal PayAsYouGoWithholdingTaxWithheldA { get; set; }

        /// <summary>
        /// Payer Total Gross Payments
        /// </summary>
        [DataMember(EmitDefaultValue = false, Order = 2)]
        public decimal TotalGrossPaymentsWithholdingA { get; set; }
    }

    /// <summary>
    /// Payroll
    /// </summary>
    [DataContract(Name = "Payroll", Namespace = "http://www.sbr.gov.au/ato/payevnt")]
    public class Payroll
    {

        /// <summary>
        /// Pay/Update Date
        /// </summary>
        [DataMember(EmitDefaultValue = false, Order = 1)]
        public DateTime PaymentRecordTransactionD { get; set; }

        /// <summary>
        /// Payee Record Count
        /// </summary>
        [DataMember(EmitDefaultValue = false, Order = 2)]
        public decimal InteractionRecordCt { get; set; }

        /// <summary>
        /// Run Date/Time Stamp
        /// </summary>
        [DataMember(EmitDefaultValue = false, Order = 3)]
        public DateTime MessageTimestampGenerationDt { get; set; }

        /// <summary>
        /// Submission ID
        /// </summary>
        [DataMember(EmitDefaultValue = false, Order = 4)]
        public string InteractionTransactionId { get; set; }

        /// <summary>
        /// Full File Replacement Indicator
        /// </summary>
        [DataMember(EmitDefaultValue = false, Order = 5)]
        public bool AmendmentI { get; set; }

        [DataMember(EmitDefaultValue = false, Order = 6)]
        public IncomeTaxAndRemuneration IncomeTaxAndRemuneration { get; set; }
    }

    /// <summary>
    /// Reporting Party Declaration
    /// </summary>
    [DataContract(Name = "Declaration", Namespace = "http://www.sbr.gov.au/ato/payevnt")]
    public class Declaration
    {

        /// <summary>
        /// Payer Declarer Identifier
        /// </summary>
        [DataMember(EmitDefaultValue = false, Order = 1)]
        public string SignatoryIdentifierT { get; set; }

        /// <summary>
        /// Payer Declaration Date
        /// </summary>
        [DataMember(EmitDefaultValue = false, Order = 2)]
        public DateTime SignatureD { get; set; }

        /// <summary>
        /// Payer Declaration Acceptance Indicator
        /// </summary>
        [DataMember(EmitDefaultValue = false, Order = 3)]
        public bool StatementAcceptedI { get; set; }
    }

    /// <summary>
    /// Reporting Party
    /// </summary>
    [DataContract(Name = "Rp", Namespace = "http://www.sbr.gov.au/ato/payevnt")]
    public class Rp
    {

        /// <summary>
        /// BMS Identifier
        /// </summary>
        [DataMember(EmitDefaultValue = false, Order = 1)]
        public string SoftwareInformationBusinessManagementSystemId { get; set; }

        /// <summary>
        /// Payer Australian Business Number
        /// </summary>
        [DataMember(EmitDefaultValue = false, Order = 2)]
        public string AustralianBusinessNumberId { get; set; }

        /// <summary>
        /// Payer Withholding Payer Number
        /// </summary>
        [DataMember(EmitDefaultValue = false, Order = 3)]
        public string WithholdingPayerNumberId { get; set; }

        /// <summary>
        /// Payer Branch Code
        /// </summary>
        [DataMember(EmitDefaultValue = false, Order = 4)]
        public string OrganisationDetailsOrganisationBranchC { get; set; }

        [DataMember(EmitDefaultValue = false, Order = 5)]
        public OrganisationName OrganisationName { get; set; }

        [DataMember(EmitDefaultValue = false, Order = 6)]
        public ElectronicContact ElectronicContact { get; set; }

        [DataMember(EmitDefaultValue = false, Order = 7)]
        public AddressDetailsPostal AddressDetailsPostal { get; set; }

        [DataMember(EmitDefaultValue = false, Order = 8)]
        public Payroll Payroll { get; set; }

        [DataMember(EmitDefaultValue = false, Order = 9)]
        public Declaration Declaration { get; set; }
    }

    /// <summary>
    /// Intermediary
    /// </summary>
    [DataContract(Name = "Int", Namespace = "http://www.sbr.gov.au/ato/payevnt")]
    public class Int
    {

        /// <summary>
        /// Intermediary ABN
        /// </summary>
        [DataMember(EmitDefaultValue = false, Order = 1)]
        public string AustralianBusinessNumberId { get; set; }

        /// <summary>
        /// Registered Agent Number
        /// </summary>
        [DataMember(EmitDefaultValue = false, Order = 2)]
        public string TaxAgentNumberId { get; set; }

        /// <summary>
        /// Intermediary Contact Name
        /// </summary>
        [DataMember(EmitDefaultValue = false, Order = 3)]
        public string PersonUnstructuredNameFullNameT { get; set; }

        [DataMember(EmitDefaultValue = false, Order = 4)]
        public ElectronicContact ElectronicContact { get; set; }

        [DataMember(EmitDefaultValue = false, Order = 5)]
        public Declaration Declaration { get; set; }
    }
}
 
