// ------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated from a template.
// 
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Generated on 2018-02-16T11:17:32, by ESR Version 1.71.0.0 using ESR Database 
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Ato.EN.IntegrationServices.CodeGenerationPAYEVNTEMP
{
    public class PAYEVNTEMP2018
    {
        public bool PayeeCollectionExists = false;
        public int PayeeCollectionCount = 0;

        public bool Payee_IdentifiersCollectionExists = false;
        public int Payee_IdentifiersCollectionCount = 0;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:Identifiers
        /// PAYEVNTEMP:pyid.02.00:Identifiers.TaxFileNumber.Identifier
        /// </summary>
        public string PAYEVNTEMP13 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:Identifiers
        /// PAYEVNTEMP:pyid.02.00:Identifiers.AustralianBusinessNumber.Identifier
        /// </summary>
        public string PAYEVNTEMP91 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:Identifiers
        /// PAYEVNTEMP:pyid.02.05:Identifiers.EmploymentPayrollNumber.Identifier
        /// </summary>
        public string PAYEVNTEMP11 = null;

        public bool Payee_PersonNameDetailsCollectionExists = false;
        public int Payee_PersonNameDetailsCollectionCount = 0;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:PersonNameDetails
        /// PAYEVNTEMP:pyde.02.00:PersonNameDetails.FamilyName.Text
        /// </summary>
        public string PAYEVNTEMP15 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:PersonNameDetails
        /// PAYEVNTEMP:pyde.02.00:PersonNameDetails.GivenName.Text
        /// </summary>
        public string PAYEVNTEMP16 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:PersonNameDetails
        /// PAYEVNTEMP:pyde.02.00:PersonNameDetails.OtherGivenName.Text
        /// </summary>
        public string PAYEVNTEMP17 = null;

        public bool Payee_PersonDemographicDetailsCollectionExists = false;
        public int Payee_PersonDemographicDetailsCollectionCount = 0;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:PersonDemographicDetails
        /// PAYEVNTEMP:pyde.02.00:PersonDemographicDetails.Birth.DayofMonth
        /// </summary>
        public int? PAYEVNTEMP205 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:PersonDemographicDetails
        /// PAYEVNTEMP:pyde.02.00:PersonDemographicDetails.Birth.Month
        /// </summary>
        public int? PAYEVNTEMP203 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:PersonDemographicDetails
        /// PAYEVNTEMP:pyde.02.00:PersonDemographicDetails.Birth.Year
        /// </summary>
        public int? PAYEVNTEMP204 = null;

        public bool Payee_AddressDetailsCollectionExists = false;
        public int Payee_AddressDetailsCollectionCount = 0;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:AddressDetails
        /// PAYEVNTEMP:pyde.02.00:AddressDetails.Line1.Text
        /// </summary>
        public string PAYEVNTEMP21 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:AddressDetails
        /// PAYEVNTEMP:pyde.02.00:AddressDetails.Line2.Text
        /// </summary>
        public string PAYEVNTEMP22 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:AddressDetails
        /// PAYEVNTEMP:pyde.02.00:AddressDetails.LocalityName.Text
        /// </summary>
        public string PAYEVNTEMP23 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:AddressDetails
        /// PAYEVNTEMP:pyde.02.00:AddressDetails.StateOrTerritory.Code
        /// </summary>
        public string PAYEVNTEMP24 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:AddressDetails
        /// PAYEVNTEMP:pyde.02.00:AddressDetails.Postcode.Text
        /// </summary>
        public string PAYEVNTEMP25 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:AddressDetails
        /// PAYEVNTEMP:pyde.02.08:AddressDetails.Country.Code
        /// </summary>
        public string PAYEVNTEMP27 = null;

        public bool Payee_ElectronicContactCollectionExists = false;
        public int Payee_ElectronicContactCollectionCount = 0;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:ElectronicContact
        /// PAYEVNTEMP:pyde.02.00:ElectronicContact.ElectronicMail.Address.Text
        /// </summary>
        public string PAYEVNTEMP94 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:ElectronicContact
        /// PAYEVNTEMP:pyde.02.00:ElectronicContact.Telephone.Minimal.Number
        /// </summary>
        public string PAYEVNTEMP95 = null;

        public bool Payee_EmployerConditionsCollectionExists = false;
        public int Payee_EmployerConditionsCollectionCount = 0;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:EmployerConditions
        /// PAYEVNTEMP:lrla.02.20:EmployerConditions.EmploymentStart.Date
        /// </summary>
        public DateTime? PAYEVNTEMP92 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:EmployerConditions
        /// PAYEVNTEMP:lrla.02.21:EmployerConditions.EmploymentEnd.Date
        /// </summary>
        public DateTime? PAYEVNTEMP93 = null;

        public bool Payee_RemunerationIncomeTaxPayAsYouGoWithholdingCollectionExists = false;
        public int Payee_RemunerationIncomeTaxPayAsYouGoWithholdingCollectionCount = 0;

        public bool Payee_RemunerationIncomeTaxPayAsYouGoWithholding_PayrollPeriodCollectionExists = false;
        public int Payee_RemunerationIncomeTaxPayAsYouGoWithholding_PayrollPeriodCollectionCount = 0;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:PayrollPeriod
        /// PAYEVNTEMP:pyin.02.00:Period.Start.Date
        /// </summary>
        public DateTime? PAYEVNTEMP29 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:PayrollPeriod
        /// PAYEVNTEMP:pyin.02.00:Period.End.Date
        /// </summary>
        public DateTime? PAYEVNTEMP30 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:PayrollPeriod
        /// PAYEVNTEMP:lrla.02.20:Remuneration.PayrollEventFinal.Indicator
        /// </summary>
        public bool? PAYEVNTEMP110 = null;

        public bool Payee_RemunerationIncomeTaxPayAsYouGoWithholding_IndividualNonBusinessCollectionExists = false;
        public int Payee_RemunerationIncomeTaxPayAsYouGoWithholding_IndividualNonBusinessCollectionCount = 0;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:IndividualNonBusiness
        /// PAYEVNTEMP:lrla.02.00:Remuneration.IndividualNonBusinessGross.Amount
        /// </summary>
        public decimal? PAYEVNTEMP47 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:IndividualNonBusiness
        /// PAYEVNTEMP:lrla.02.00:Remuneration.IndividualNonBusinessCommunityDevelopmentEmploymentProject.Amount
        /// </summary>
        public decimal? PAYEVNTEMP60 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:IndividualNonBusiness
        /// PAYEVNTEMP:rvctc2.02.12:IncomeTax.PayAsYouGoWithholding.TaxWithheld.Amount
        /// </summary>
        public decimal? PAYEVNTEMP130 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:IndividualNonBusiness
        /// PAYEVNTEMP:lrla.02.01:Remuneration.IndividualNonBusinessExemptForeignEmploymentIncome.Amount
        /// </summary>
        public decimal? PAYEVNTEMP49 = null;

        public bool Payee_RemunerationIncomeTaxPayAsYouGoWithholding_VoluntaryAgreementCollectionExists = false;
        public int Payee_RemunerationIncomeTaxPayAsYouGoWithholding_VoluntaryAgreementCollectionCount = 0;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:VoluntaryAgreement
        /// PAYEVNTEMP:lrla.02.00:Remuneration.VoluntaryAgreementGross.Amount
        /// </summary>
        public decimal? PAYEVNTEMP57 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:VoluntaryAgreement
        /// PAYEVNTEMP:rvctc2.02.12:IncomeTax.PayAsYouGoWithholding.TaxWithheld.Amount
        /// </summary>
        public decimal? PAYEVNTEMP115 = null;

        public bool Payee_RemunerationIncomeTaxPayAsYouGoWithholding_LabourHireArrangementPaymentCollectionExists = false;
        public int Payee_RemunerationIncomeTaxPayAsYouGoWithholding_LabourHireArrangementPaymentCollectionCount = 0;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:LabourHireArrangementPayment
        /// PAYEVNTEMP:lrla.02.00:Remuneration.LabourHireArrangementPaymentGross.Amount
        /// </summary>
        public decimal? PAYEVNTEMP48 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:LabourHireArrangementPayment
        /// PAYEVNTEMP:rvctc2.02.12:IncomeTax.PayAsYouGoWithholding.TaxWithheld.Amount
        /// </summary>
        public decimal? PAYEVNTEMP114 = null;

        public bool Payee_RemunerationIncomeTaxPayAsYouGoWithholding_SpecifiedByRegulationPaymentCollectionExists = false;
        public int Payee_RemunerationIncomeTaxPayAsYouGoWithholding_SpecifiedByRegulationPaymentCollectionCount = 0;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:SpecifiedByRegulationPayment
        /// PAYEVNTEMP:lrla.02.00:Remuneration.SpecifiedByRegulationPaymentGross.Amount
        /// </summary>
        public decimal? PAYEVNTEMP122 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:SpecifiedByRegulationPayment
        /// PAYEVNTEMP:rvctc2.02.12:IncomeTax.PayAsYouGoWithholding.TaxWithheld.Amount
        /// </summary>
        public decimal? PAYEVNTEMP116 = null;

        public bool Payee_RemunerationIncomeTaxPayAsYouGoWithholding_JointPetroleumDevelopmentAreaPaymentCollectionExists = false;
        public int Payee_RemunerationIncomeTaxPayAsYouGoWithholding_JointPetroleumDevelopmentAreaPaymentCollectionCount = 0;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:JointPetroleumDevelopmentAreaPayment
        /// PAYEVNTEMP:lrla.02.21:Remuneration.JointPetroleumDevelopmentAreaPayment.Amount
        /// </summary>
        public decimal? PAYEVNTEMP120 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:JointPetroleumDevelopmentAreaPayment
        /// PAYEVNTEMP:rvctc1.02.29:IncomeTax.ForeignWithholding.Amount
        /// </summary>
        public decimal? PAYEVNTEMP132 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:JointPetroleumDevelopmentAreaPayment
        /// PAYEVNTEMP:rvctc2.02.12:IncomeTax.PayAsYouGoWithholding.TaxWithheld.Amount
        /// </summary>
        public decimal? PAYEVNTEMP113 = null;

        public bool Payee_RemunerationIncomeTaxPayAsYouGoWithholding_WorkingHolidayMakerCollectionExists = false;
        public int Payee_RemunerationIncomeTaxPayAsYouGoWithholding_WorkingHolidayMakerCollectionCount = 0;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:WorkingHolidayMaker
        /// PAYEVNTEMP:lrla.02.22:Remuneration.WorkingHolidayMakerGross.Amount
        /// </summary>
        public decimal? PAYEVNTEMP200 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:WorkingHolidayMaker
        /// PAYEVNTEMP:rvctc2.02.12:IncomeTax.PayAsYouGoWithholding.TaxWithheld.Amount
        /// </summary>
        public decimal? PAYEVNTEMP201 = null;

        public bool Payee_RemunerationIncomeTaxPayAsYouGoWithholding_PaymentToForeignResidentCollectionExists = false;
        public int Payee_RemunerationIncomeTaxPayAsYouGoWithholding_PaymentToForeignResidentCollectionCount = 0;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:PaymentToForeignResident
        /// PAYEVNTEMP:lrla.02.00:Remuneration.PaymentToForeignResidentGross.Amount
        /// </summary>
        public decimal? PAYEVNTEMP119 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:PaymentToForeignResident
        /// PAYEVNTEMP:rvctc2.02.29:IncomeTax.ForeignWithholding.Amount
        /// </summary>
        public decimal? PAYEVNTEMP237 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:PaymentToForeignResident
        /// PAYEVNTEMP:rvctc2.02.12:IncomeTax.PayAsYouGoWithholding.TaxWithheld.Amount
        /// </summary>
        public decimal? PAYEVNTEMP112 = null;

        public bool Payee_RemunerationIncomeTaxPayAsYouGoWithholding_EmploymentTerminationPaymentCollectionExists = false;
        public int Payee_RemunerationIncomeTaxPayAsYouGoWithholding_EmploymentTerminationPaymentCollectionCount = 0;

        public List<Payee_RemunerationIncomeTaxPayAsYouGoWithholding_EmploymentTerminationPayment> Payee_RemunerationIncomeTaxPayAsYouGoWithholding_EmploymentTerminationPaymentCollection = null;

        public class Payee_RemunerationIncomeTaxPayAsYouGoWithholding_EmploymentTerminationPayment
        {
            public int OccurrenceIndex = 0;

            /// <summary>
            /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:EmploymentTerminationPayment
            /// PAYEVNTEMP:rvctc2.02.11:IncomeTax.PayAsYouGoWithholding.EmploymentTerminationPaymentType.Code
            /// </summary>
            public string PAYEVNTEMP34 = null;

            /// <summary>
            /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:EmploymentTerminationPayment
            /// PAYEVNTEMP:pyin.02.00:PaymentRecord.PaymentEffective.Date
            /// </summary>
            public DateTime? PAYEVNTEMP123 = null;

            /// <summary>
            /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:EmploymentTerminationPayment
            /// PAYEVNTEMP:rvctc2.02.10:IncomeTax.Superannuation.TaxFreeComponent.Amount
            /// </summary>
            public decimal? PAYEVNTEMP50 = null;

            /// <summary>
            /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:EmploymentTerminationPayment
            /// PAYEVNTEMP:rvctc2.02.00:IncomeTax.Superannuation.EmploymentTerminationTaxableComponentTotal.Amount
            /// </summary>
            public decimal? PAYEVNTEMP51 = null;

            /// <summary>
            /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:EmploymentTerminationPayment
            /// PAYEVNTEMP:rvctc2.02.12:IncomeTax.PayAsYouGoWithholding.TaxWithheld.Amount
            /// </summary>
            public decimal? PAYEVNTEMP117 = null;
        }

        public bool Payee_RemunerationIncomeTaxPayAsYouGoWithholding_UnusedAnnualOrLongServiceLeavePaymentCollectionExists = false;
        public int Payee_RemunerationIncomeTaxPayAsYouGoWithholding_UnusedAnnualOrLongServiceLeavePaymentCollectionCount = 0;

        public bool Payee_RemunerationIncomeTaxPayAsYouGoWithholding_UnusedAnnualOrLongServiceLeavePayment_LumpSumPaymentACollectionExists = false;
        public int Payee_RemunerationIncomeTaxPayAsYouGoWithholding_UnusedAnnualOrLongServiceLeavePayment_LumpSumPaymentACollectionCount = 0;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:UnusedAnnualOrLongServiceLeavePayment/:LumpSumPaymentA
        /// PAYEVNTEMP:lrla.02.00:Remuneration.UnusedAnnualOrLongServiceLeavePaymentLumpSumA.Code
        /// </summary>
        public string PAYEVNTEMP53 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:UnusedAnnualOrLongServiceLeavePayment/:LumpSumPaymentA
        /// PAYEVNTEMP:lrla.02.00:Remuneration.UnusedAnnualOrLongServiceLeavePaymentLumpSumA.Amount
        /// </summary>
        public decimal? PAYEVNTEMP52 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:UnusedAnnualOrLongServiceLeavePayment
        /// PAYEVNTEMP:lrla.02.00:Remuneration.UnusedAnnualOrLongServiceLeavePaymentLumpSumB.Amount
        /// </summary>
        public decimal? PAYEVNTEMP54 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:UnusedAnnualOrLongServiceLeavePayment
        /// PAYEVNTEMP:lrla.02.00:Remuneration.UnusedAnnualOrLongServiceLeavePaymentLumpSumD.Amount
        /// </summary>
        public decimal? PAYEVNTEMP55 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:UnusedAnnualOrLongServiceLeavePayment
        /// PAYEVNTEMP:lrla.02.00:Remuneration.UnusedAnnualOrLongServiceLeavePaymentLumpSumE.Amount
        /// </summary>
        public decimal? PAYEVNTEMP56 = null;

        public bool Payee_RemunerationIncomeTaxPayAsYouGoWithholding_AllowanceCollectionExists = false;
        public int Payee_RemunerationIncomeTaxPayAsYouGoWithholding_AllowanceCollectionCount = 0;

        public List<Payee_RemunerationIncomeTaxPayAsYouGoWithholding_Allowance> Payee_RemunerationIncomeTaxPayAsYouGoWithholding_AllowanceCollection = null;

        public class Payee_RemunerationIncomeTaxPayAsYouGoWithholding_Allowance
        {
            public int OccurrenceIndex = 0;

            /// <summary>
            /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:Allowance
            /// PAYEVNTEMP:lrla.02.20:Remuneration.AllowanceType.Code
            /// </summary>
            public string PAYEVNTEMP7 = null;

            /// <summary>
            /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:Allowance
            /// PAYEVNTEMP:lrla.02.20:IncomeTax.OtherAllowanceType.Description
            /// </summary>
            public string PAYEVNTEMP8 = null;

            /// <summary>
            /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:Allowance
            /// PAYEVNTEMP:lrla.02.20:Remuneration.IndividualNonBusinessEmploymentAllowances.Amount
            /// </summary>
            public decimal? PAYEVNTEMP62 = null;
        }

        public bool Payee_RemunerationIncomeTaxPayAsYouGoWithholding_DeductionCollectionExists = false;
        public int Payee_RemunerationIncomeTaxPayAsYouGoWithholding_DeductionCollectionCount = 0;

        public List<Payee_RemunerationIncomeTaxPayAsYouGoWithholding_Deduction> Payee_RemunerationIncomeTaxPayAsYouGoWithholding_DeductionCollection = null;

        public class Payee_RemunerationIncomeTaxPayAsYouGoWithholding_Deduction
        {
            public int OccurrenceIndex = 0;

            /// <summary>
            /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:Deduction
            /// PAYEVNTEMP:lrla.02.20:Remuneration.DeductionType.Code
            /// </summary>
            public string PAYEVNTEMP10 = null;

            /// <summary>
            /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:Deduction
            /// PAYEVNTEMP:lrla.02.21:Remuneration.Deduction.Amount
            /// </summary>
            public decimal? PAYEVNTEMP87 = null;
        }

        public bool Payee_RemunerationIncomeTaxPayAsYouGoWithholding_SuperannuationContributionCollectionExists = false;
        public int Payee_RemunerationIncomeTaxPayAsYouGoWithholding_SuperannuationContributionCollectionCount = 0;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:SuperannuationContribution
        /// PAYEVNTEMP:emsup.02.08:SuperannuationContribution.EmployerContributionsSuperannuationGuarantee.Amount
        /// </summary>
        public decimal? PAYEVNTEMP84 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:SuperannuationContribution
        /// PAYEVNTEMP:lrla.02.20:Remuneration.OrdinaryTimeEarnings.Amount
        /// </summary>
        public decimal? PAYEVNTEMP61 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:SuperannuationContribution
        /// PAYEVNTEMP:emsup.02.19:SuperannuationContribution.EmployerReportable.Amount
        /// </summary>
        public decimal? PAYEVNTEMP111 = null;

        public bool Payee_RemunerationIncomeTaxPayAsYouGoWithholding_IncomeFringeBenefitsReportableCollectionExists = false;
        public int Payee_RemunerationIncomeTaxPayAsYouGoWithholding_IncomeFringeBenefitsReportableCollectionCount = 0;

        public bool Payee_RemunerationIncomeTaxPayAsYouGoWithholding_IncomeFringeBenefitsReportable_TaxableCollectionExists = false;
        public int Payee_RemunerationIncomeTaxPayAsYouGoWithholding_IncomeFringeBenefitsReportable_TaxableCollectionCount = 0;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:IncomeFringeBenefitsReportable/:Taxable
        /// PAYEVNTEMP:bafpr1.02.32:Income.FringeBenefitsReportable.Amount
        /// </summary>
        public decimal? PAYEVNTEMP125 = null;

        public bool Payee_RemunerationIncomeTaxPayAsYouGoWithholding_IncomeFringeBenefitsReportable_ExemptCollectionExists = false;
        public int Payee_RemunerationIncomeTaxPayAsYouGoWithholding_IncomeFringeBenefitsReportable_ExemptCollectionCount = 0;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:RemunerationIncomeTaxPayAsYouGoWithholding/:IncomeFringeBenefitsReportable/:Exempt
        /// PAYEVNTEMP:bafpr1.02.23:Income.FringeBenefitsReportable.Amount
        /// </summary>
        public decimal? PAYEVNTEMP126 = null;

        public bool Payee_OnboardingCollectionExists = false;
        public int Payee_OnboardingCollectionCount = 0;

        public bool Payee_Onboarding_TFNDCollectionExists = false;
        public int Payee_Onboarding_TFNDCollectionCount = 0;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:Onboarding/:TFND
        /// PAYEVNTEMP:pypl.02.00:PaymentArrangement.Termination.Code
        /// </summary>
        public string PAYEVNTEMP238 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:Onboarding/:TFND
        /// PAYEVNTEMP:pyde.02.35:Residency.TaxPurposesPersonStatus.Code
        /// </summary>
        public string PAYEVNTEMP202 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:Onboarding/:TFND
        /// PAYEVNTEMP:pylk.02.00:PaymentArrangement.PaymentBasis.Code
        /// </summary>
        public string PAYEVNTEMP96 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:Onboarding/:TFND
        /// PAYEVNTEMP:gfati.02.00:TaxOffsetClaim.TaxFreeThreshold.Indicator
        /// </summary>
        public bool? PAYEVNTEMP98 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:Onboarding/:TFND
        /// PAYEVNTEMP:rctc2.02.27:IncomeTax.PayAsYouGoWithholding.StudyAndTrainingLoanRepayment.Indicator
        /// </summary>
        public bool? PAYEVNTEMP241 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:Onboarding/:TFND
        /// PAYEVNTEMP:edte.02.00:StudentLoan.StudentFinancialSupplementScheme.Indicator
        /// </summary>
        public bool? PAYEVNTEMP106 = null;

        public bool Payee_Onboarding_DeclarationCollectionExists = false;
        public int Payee_Onboarding_DeclarationCollectionCount = 0;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:Onboarding/:Declaration
        /// PAYEVNTEMP:pyin.02.28:Declaration.StatementAccepted.Indicator
        /// </summary>
        public bool? PAYEVNTEMP129 = null;

        /// <summary>
        /// /xbrli:xbrl/:Payee/:Onboarding/:Declaration
        /// PAYEVNTEMP:pyin.02.29:Declaration.Signature.Date
        /// </summary>
        public DateTime? PAYEVNTEMP128 = null;

    }
}
